apiVersion: v1
externalServicesDeclarations:
- name: isc-sds-prometheus-ui
  type: loadBalancer
  hostnameChartField: isc-sds-prometheus-ui.hostname
  loadBalancerPortChartField: isc-sds-prometheus-ui.port
  enabled: false
  enabledChartField: isc-sds-prometheus-ui.enabled
  label: Prometheus UI
  description: Port to access the Prometheus UI over a Load Balancer
- name: isc-sds-grafana-ui
  type: loadBalancer
  hostnameChartField: isc-sds-grafana-ui.hostname
  loadBalancerPortChartField: isc-sds-grafana-ui.port
  enabled: false
  enabledChartField: isc-sds-grafana-ui.enabled
  label: Grafana UI
  description: Port to access the Grafana UI over a Load Balancer
endpoints:
- title: Grafana UI
  group: Developer
  description: Open the Grafana UI in your browser
  type: browsing
  url: http://{externalService.host}:{externalService.port}/
  contexts:
  - portal
  - manage
  visibility: external
  presentation: link
  externalService: ui
  