image: ubuntu:22.04

cloudProvider: "dev"
cloudProviderRegion: "dev-region"
compute:
  main:
    nodeTypeSelector: ""
    cpu: 100m
    memory: 512Mi

# These are the secret fields needed to successfully deploy.
# They will be injected by the control plane:
requiredSecrets:
  intersystemsContainerRegistrySecret: ""
